spring: #띄워쓰기 없음
  datasource: #띄워쓰기 2칸
    url: jdbc:mysql://localhost:3306/elice_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: pro_user
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: update #띄어쓰기 6칸 -- create / update / validate / none
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
  logging.level: #띄어쓰기 없음
    org.hibernate.SQL: debug #띄어쓰기 2칸4칸
  thymeleaf:
    suffix: .html
    cache: false


